{% set version = "5.9.9" %}
{% set ver = '.'.join(version.split('.')[:2]) %}

package:
  name: qtserialport
  version: {{ version }}

source:
  url: http://download.qt.io/official_releases/qt/{{ ver }}/{{ version }}/submodules/qtserialport-opensource-src-{{ version }}.tar.xz
  sha256: 65c2fa8add33c96afd2937feaa8f8a1e2b5c429319946a3beca85c666bf17c23

build:
  # QtSerialPort already comes with Windows Qt builds but the included bld.bat
  # should work (just doesn't package anything because files already exist)
  skip: true  # [win]
  number: 0

requirements:
  build:
    - perl
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - qt
  run:
    - qt

test:
  commands:
    - test -f ${PREFIX}/lib/libQt5SerialPort${SHLIB_EXT}  # [not win]

about:
  home: https://github.com/qt/qtserialport
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.GPL3
  summary: 'The QtSerialPort module is an add-on module for the Qt5 library, providing a single interface for both hardware and virtual serial ports.'
  description: |
    The QtSerialPort module is an add-on module for the Qt5 library, providing a single
    interface for both hardware and virtual serial ports. Serial interfaces, due to
    their simplicity and reliability, are still popular in some industries like the
    development of embedded systems, robotics, etc. Using the QtSerialPort module,
    developers can significantly reduce the time needed to implement Qt applications
    that require access to a serial interface.
  doc_url: http://doc.qt.io/qt-5/qtserialport-index.html
  dev_url: https://github.com/qt/qtserialport

extra:
  recipe-maintainers:
    - ceholden
